import React, { useState } from "react";
import { deleteDoc, doc } from "firebase/firestore";
import { ChevronDown, ChevronUp, Trash2, Loader2 } from "lucide-react";
import { WordItemProps } from "../types";
import { formatDate } from "../utils/dateUtils";
import { firebaseConfig } from "../config/firebase";

export const WordItem: React.FC<WordItemProps> = ({ word, onSelect, db }) => {
  const [isExpanded, setIsExpanded] = useState<boolean>(false);
  const docPath = `/artifacts/${firebaseConfig.projectId}/public/data/words`;

  const toggleExpand = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.stopPropagation();
    setIsExpanded(!isExpanded);
  };

  const handleDelete = async (
    e: React.MouseEvent<HTMLButtonElement>,
    wordId: string,
  ) => {
    e.stopPropagation();
    if (!db) return;

    console.log(`Simulating confirmation for deletion of word ID: ${wordId}`);
    try {
      const docRef = doc(db, docPath, wordId);
      await deleteDoc(docRef);
      console.log("Document successfully deleted!");
    } catch (error) {
      console.error("Error removing document: ", error);
    }
  };

  const hasDetails = !!word.definition;
  const isFetching = word.isFetchingDetails;
  // try to read local cached details for preview
  let localPreviewDefinition: string | null = null;
  try {
    const raw = localStorage.getItem(`word-details-${word.id}`);
    if (raw) {
      const parsed = JSON.parse(raw);
      const details = parsed.details || parsed;
      if (details && details.definition)
        localPreviewDefinition = details.definition;
    }
  } catch {
    // ignore
  }

  return (
    <div className="card">
      <div
        className="cursor-pointer hover:bg-opacity-50 transition-colors flex-between"
        onClick={() => onSelect(word.id)}
      >
        <div className="flex-1 min-w-0">
          <h3 className="text-lg font-semibold">
            {word.word}
            {word.partOfSpeech && (
              <span className="text-sm font-normal ml-2 text-muted">
                ({word.partOfSpeech})
              </span>
            )}
          </h3>
          <p className="text-sm text-muted mt-md">
            Added: {formatDate(word.dateAdded)}
          </p>
        </div>
        <div className="flex items-center space-x-2 ml-lg">
          {isFetching ? (
            <span className="accent flex items-center text-sm">
              <Loader2 className="w-4 h-4 animate-spin mr-sm icon" />{" "}
              Generating...
            </span>
          ) : (
            <button
              onClick={toggleExpand}
              className="p-1 hover:bg-surface rounded-full transition-colors"
              aria-label={
                isExpanded ? "Collapse details" : "Expand definition summary"
              }
            >
              {isExpanded ? (
                <ChevronUp className="w-5 h-5 icon" />
              ) : (
                <ChevronDown className="w-5 h-5 icon" />
              )}
            </button>
          )}
          <button
            onClick={(e) => handleDelete(e, word.id)}
            className="p-1 text-error hover:bg-surface rounded-full transition-colors"
            title="Delete Word"
            aria-label="Delete word"
          >
            <Trash2 className="w-5 h-5 icon" />
          </button>
        </div>
      </div>

      <div
        className={`overflow-hidden transition-[max-height] duration-300 ease-in-out border-t border-border/50 
                           ${
                             isExpanded
                               ? "max-h-96 opacity-100"
                               : "max-h-0 opacity-0 border-t-0"
                           }`}
      >
        <div className="pt-md mt-md">
          <p className="text-base">
            {localPreviewDefinition ? (
              localPreviewDefinition
            ) : word.definition && hasDetails ? (
              word.definition
            ) : isFetching ? (
              <span className="accent italic">
                Definition is being generated by AI...
              </span>
            ) : (
              <span className="text-muted italic">
                No definition available. Click to view details and generate!
              </span>
            )}
          </p>
          <button
            onClick={() => onSelect(word.id)}
            className="mt-md text-accent hover:text-accent-dark text-sm font-medium"
          >
            View Full Details →
          </button>
        </div>
      </div>
    </div>
  );
};
