import React, { useState } from "react";
import { deleteDoc, doc } from "firebase/firestore";
import { ChevronDown, ChevronUp, Trash2, Loader2 } from "lucide-react";
import { WordItemProps } from "../types";
import { formatDate } from "../utils/dateUtils";
import { firebaseConfig } from "../config/firebase";

export const WordItem: React.FC<WordItemProps> = ({ word, onSelect, db }) => {
  const [isExpanded, setIsExpanded] = useState<boolean>(false);
  const docPath = `/artifacts/${firebaseConfig.projectId}/public/data/words`;

  const toggleExpand = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.stopPropagation();
    setIsExpanded(!isExpanded);
  };

  const handleDelete = async (
    e: React.MouseEvent<HTMLButtonElement>,
    wordId: string
  ) => {
    e.stopPropagation();
    if (!db) return;

    console.log(`Simulating confirmation for deletion of word ID: ${wordId}`);
    try {
      const docRef = doc(db, docPath, wordId);
      await deleteDoc(docRef);
      console.log("Document successfully deleted!");
    } catch (error) {
      console.error("Error removing document: ", error);
    }
  };

  const hasDetails = !!word.definition;
  const isFetching = word.isFetchingDetails;

  return (
    <div className="flex flex-col bg-slate-800 border border-slate-700 rounded-xl shadow-md transition-shadow hover:shadow-lg">
      <div
        className="p-4 cursor-pointer hover:bg-slate-700/50 transition-colors rounded-t-xl flex justify-between items-center"
        onClick={() => onSelect(word.id)}
      >
        <div className="flex-1 min-w-0">
          <h3 className="text-xl font-semibold text-white truncate">
            {word.word}
            {word.partOfSpeech && (
              <span className="text-sm font-normal ml-2 text-slate-400">
                ({word.partOfSpeech})
              </span>
            )}
          </h3>
          <p className="text-sm text-slate-500 mt-1">
            Added: {formatDate(word.dateAdded)}
          </p>
        </div>
        <div className="flex items-center space-x-2 ml-4">
          {isFetching ? (
            <span className="text-sky-400 flex items-center text-sm">
              <Loader2 className="w-4 h-4 animate-spin mr-1" /> Generating...
            </span>
          ) : (
            <button
              onClick={toggleExpand}
              className="p-1 text-slate-400 hover:text-white rounded-full transition-colors"
              aria-label={
                isExpanded ? "Collapse details" : "Expand definition summary"
              }
            >
              {isExpanded ? (
                <ChevronUp className="w-5 h-5" />
              ) : (
                <ChevronDown className="w-5 h-5" />
              )}
            </button>
          )}
          <button
            onClick={(e) => handleDelete(e, word.id)}
            className="p-1 text-red-400 hover:text-red-300 rounded-full transition-colors"
            title="Delete Word"
            aria-label="Delete word"
          >
            <Trash2 className="w-5 h-5" />
          </button>
        </div>
      </div>

      <div
        className={`overflow-hidden transition-[max-height] duration-300 ease-in-out border-t border-slate-700/50 
                           ${
                             isExpanded
                               ? "max-h-96 opacity-100"
                               : "max-h-0 opacity-0 border-t-0"
                           }`}
      >
        <div className="p-4 pt-3">
          <p className="text-slate-300 text-base">
            {word.definition && hasDetails ? (
              word.definition
            ) : isFetching ? (
              <span className="text-sky-400 italic">
                Definition is being generated by AI...
              </span>
            ) : (
              <span className="text-slate-500 italic">
                No definition available. Click to view details and generate!
              </span>
            )}
          </p>
          <button
            onClick={() => onSelect(word.id)}
            className="mt-2 text-sky-400 hover:text-sky-300 text-sm font-medium"
          >
            View Full Details →
          </button>
        </div>
      </div>
    </div>
  );
};
